on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: 'Version'
        required: true

permissions:
  contents: write
  pull-requests: write

name: release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        id: neovim
        with:
          neovim: true
          version: v0.10.3
      - name: Update changelog
        run: |
          nvim -l scripts/generate_changelog.lua ${{ github.event.inputs.version }}
      - name: Print generated changelog
        run: |
          cat docs/changelog.org
      - name: Get release info
        id: release_info
        run: |
          changes=$(nvim -l scripts/generate_changelog.lua ${{ github.event.inputs.version }} print)
          {
            echo 'output<<EOF'
            echo "$changes"
            echo 'EOF'
          } >> $GITHUB_OUTPUT
      # - name: Tag new version
        # run: |
        #   git tag -a ${{ github.event.inputs.version }} -m "Release ${{ github.evente.inputs.version }}"
      - name: Print release info
        run:
          echo "${{ steps.release_info.outputs.output }}"
